version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: master
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: develop
  versioning-strategy: lockfile-only
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
    timezone: Europe/Vienna
  open-pull-requests-limit: 10
  target-branch: initial-setup
  versioning-strategy: lockfile-only
